### ISSUE TITLE
FilterMap pipe

### ISSUE THREAD

**Issue by platers** [pytorch/data#1059]
### 🚀 The feature

A new iterable datapipe that maps a function, then filters the results.

### Motivation, pitch

A common operation is applying a map, then filtering results. For example, downloading files, and filtering the failed downloads. This requires a map and a filter pipe. It would be more elegant to combine them into a single pipe.

### Additional context

Similar idea as https://doc.rust-lang.org/std/iter/struct.FilterMap.html

**Comment by ejguan** [comment]
Hi, thanks for requesting new feature for TorchData.
TBH, I am not sure how significant of such a syntax sugar:
```py
dp.map(map_fn).filter(filter_fn)
```
In terms of the reference from rust, it's more complicated as it requires another `map` to unpack the result, which is not the expected behavior of TorchData.

And, if any Error happens within `map_fn`, `map` DataPipe will raise Error directly as we don't provide a handle/future for you to check result `is_ok()`. This feature request might be related to yours https://github.com/pytorch/data/issues/962 to add a way to handle Exception during iteration. We might want to do a DataPipe to skip over the Exception from the prior DataPipe and continue to yield data.

**Comment by platers** [comment]
#962 would be perfect for my use cases. Either of these features would make the syntax cleaner IMO. Every stage of my datapipe can raise exceptions, so I end up with something like 

```
dp
.map(map_fn1)
.filter(exists)
.map(map_fn2)
.filter(exists)
.map(map_fn3)
.filter(exists)
.map(map_fn4)
.filter(exists)
.map(map_fn5)
.filter(exists)
```

**Comment by platers** [comment]
1. Downloading files from cloud which may fail due to network.
2. Searching for the corresponding label in a database, which may not exist
3. Loading the file into memory, which can fail if the file is corrupted

My datasource is constantly changing and very messy so many steps can fail.

**Comment by NivekT** [comment]
In theory, you can use `flapmap` and have the function returns an empty list where there is an exception or needs to skip for any other reason. In the flatten step, the empty lists will automatically be dropped. I can see how it can be helpful, it stops short of "retry" though.

```python
def _fn(x):
    if x % 2 == 0:
        return []
    else:
        return [x * 10]


dp = IterableWrapper(list(range(10))).flatmap(_fn)
```

**Comment by platers** [comment]
I ended up implementing a try map pipe which solves my problems. Closing because #962 covers this use case. Thanks!

**Comment by NivekT** [comment]
Glad you solved your issue @platers. If you would like to comment on #962 about what you ended up implementing, that may be helpful to others in the feature. Thanks!
