### ISSUE TITLE
Is torchdata still being actively developed? 

### ISSUE THREAD

**Issue by lendle** [pytorch/data#1192]
No commits since June 7 (3 weeks ago). And @ejguan  mentioned in https://github.com/pytorch/data/issues/1184#issuecomment-1593476769 they and @NivekT, the primary contributors, are no longer working on it. 

Can anyone comment on whether torchdata will continue to be developed or supported?

**Comment by ejguan** [comment]
cc: @laurencer

**Comment by rbavery** [comment]
Sorry for the ping, but I'm very curious to hear updates on this! My colleague has developed a lib on top of torchdata for streaming and chipping satellite imagery: https://zen3geo.readthedocs.io/en/latest/walkthrough.html I'm curious if we can expect torchdata to be carried through to a stable release and be actively developed beyond that.

**Comment by magehrig** [comment]
It would be nice to update the Readme if the following is not true anymore: "We are committed to bring this library to stable release, ..."

**Comment by laurencer** [comment]
Hi folks - I'll be updating the README shortly and also adding a pinned issue here to collect feedback.

As of July 2023, we have paused active development on TorchData and will pause new releases. We have learnt a lot from building it and hearing from users, but also believe we need to re-evaluate the technical design and approach given how much the industry has changed since we began the project. 

During the rest of 2023 we will be re-evaluating our plans in this space. Data loading is really important and we want to make sure we're able to solve the problem effectively. Please reach out if you have any suggestions or comments.

**Comment by jamesparsloe** [comment]
> but also believe we need to re-evaluate the technical design and approach given how much the industry has changed since we began the project.

Would be interested to know what areas you think aren't working well or aren't suitable for building upon for the future? Are there alternative approaches/examples to TorchData you would recommend using in the meantime? Appreciate it might be too soon to say. Thanks.

**Comment by laurencer** [comment]
Please see #1196 for a full update!
