### ISSUE TITLE
`_get_response_from_http` doesn't work on Colab.

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#232]
### 🐛 Describe the bug

Code ponter here:
https://github.com/pytorch/data/blob/6c5a9cb040740db1c5385fe9cc6ca3e5307d49f0/torchdata/datapipes/iter/load/online.py#L13

Faling code:
```py
import requests
with requests.Session() as session:
    r = session.get(url, stream=True)
    print(r.raw.read())
```

Code with right result:
```py
import requests
with requests.Session() as session:
    r = session.get(url, stream=True)
    print(r.text)
```

![image](https://user-images.githubusercontent.com/68879799/154581876-d9784ef6-1eef-48a6-bcce-063eccccdf98.png)

### Versions

main

**Comment by ejguan** [comment]
I will check what I can fix tomorrow. It seems this only happens on colab. The tests on our CI are consistently succeeded on Linux/Mac/Windows.
Just let you know about this bug. cc: @NivekT

**Comment by Nayef211** [comment]
@parmeet just as a fyi, this is why the text classification tutorial was failing on Collab.

**Comment by Nayef211** [comment]
> And, the reason it happens on Colab is:
> 
> > google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.

@ejguan thanks for fixing this issue to help unblock breakages in torchtext's text classification tutorial!

**Comment by Nayef211** [comment]
I just want to verify. Do we need to add the following line to our tutorial moving forward?
`!pip install "urllib3>=1.25" requests --no-cache-dir`

It seems like the classification tutorial is still failing unless the above line is added. However, since you specify `urllib3 >= 1.25` in the torchdata requirements.txt file, shouldn't this ensure that pip upgrades the system version of `urllib` to satisfy the version requirements?

**Comment by ejguan** [comment]
Yes. It will be updated today in RC release.
