### ISSUE TITLE
Also expose `torch` native datapipes in `torchdata.datapipes`

### ISSUE THREAD

**Issue by pmeier** [pytorch/data#27]
That would remove the need to import these from three different sources.

Before:

```python
from torch.utils.data import IterDataPipe
from torch.utils.data.datapipes.iter import (
    Demultiplexer,
    Filter,
    Mapper,
    TarArchiveReader,
    Shuffler,
)
from torchdata.datapipes.iter import KeyZipper
```

After:

```python
from torchdata.datapipes.iter import (
    KeyZipper,
    IterDataPipe,
    Demultiplexer,
    Filter,
    Mapper,
    TarArchiveReader,
    Shuffler,
)
```

I can send a PR if we want this.

**Comment by ejguan** [comment]
That's a good idea to have a single source of Truth. And, we need to carefully take care of duplicated DataPipes like `TarArchiveReader`

**Comment by pmeier** [comment]
> That's a good idea to have a single source of Truth. And, we need to carefully take care of duplicated DataPipes like `TarArchiveReader` without overriding them from data repo.

The second part sound that there is no single source of truth if `torchdata.datapipes` diverges from `torch.utils.data.datapipes`. Looking at `TarArchiveReader`, I found this

https://github.com/pytorch/data/blob/77c07bffb83516fe11eaa425d1d1bb3b5a731174/torchdata/datapipes/iter/util/tararchivereader.py#L11-L12

So what is the plan here? Remove everything from `torch.utils.data.datapipes` that is also in `torchdata.datapipes` and import and expose the rest?

**Comment by ejguan** [comment]
We added a deprecation warning in PyTorch
https://github.com/pytorch/pytorch/blob/e3af4be96338d0645310e7cab47ce78509a6603e/torch/utils/data/datapipes/iter/tararchivereader.py#L37
We will remove them in the next release after 1.10. Before that, if any user imports DataPipe from torchdata, they should use the one in torchdata rather than the one in pytorch core.

For the list of duplicated DataPipes, we should not expose them from PyTorch core to torchdata but directly use the implementation from torchdata.

**Comment by pmeier** [comment]
I'll send a PR.
