### ISSUE TITLE
Blog post about torch data

### ISSUE THREAD

**Issue by tcapelle** [pytorch/data#307]
### 📚 The doc issue

Hello,
I have been looking at torchdata for a while now, so once it got released I decided to write about it!
I put together a small article about the usage here:
http://wandb.me/torchdata

Would really love feedback on this.

cc. @ejguan @msaroufim

### Suggest a potential alternative/fix

-

**Comment by NivekT** [comment]
Thank you so much for using our library and writing a blog post! It looks great!

We re-wrote some part of our README due to user feedback, partly because in PyTorch there is a class `Dataset`,  so we are being extra careful while using that word. Do you mind changing the follow?

"A library that enables building DataSets with building blocks"
to
"A library that enable building datasets with reusable building blocks called [`DataPipes`](https://github.com/pytorch/data#what-are-datapipes)"

In another note, here is a [link to our documentation website](https://pytorch.org/data/beta/index.html) that users may be interested to see. It has a comprehensive list of built-in DataPipes available for users.

Thanks again!

cc: @VitalyFedyunin

**Comment by tcapelle** [comment]
Thanks for the feedback, I modified the text and added a link to the documentation.

**Comment by tcapelle** [comment]
Hello again, 
Should I make a PR to add this example somewhere?

**Comment by NivekT** [comment]
Hi,

I see that you have Jupyter notebooks. I think the options we have are:
1. If the source data can be downloaded as part of the notebooks, we can add those notebooks into the `examples/` directory.
2. We can make an additional page on the documentation site by converting the blog post into a new RST file in `docs/source`.

Perhaps, we can potentially link to the blog post from our documentation as an external example but we will not be able to update the source code or content if the API changes over time.

**Comment by tcapelle** [comment]
That would be great! I really enjoying torchdata a lot!

**Comment by VitalyFedyunin** [comment]
super nit: I believe our doc engine also supports MD format and notebooks format.

**Comment by NivekT** [comment]
Closed by #340
