### ISSUE TITLE
AWS S3 DataPipe doesn't terminate when used with `.load_from_tar(mode="r|")`

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#799]
### 🐛 Describe the bug

Note this issue only occurs when `mode="r|"`, not when it is `mode="r:"`.

Sample code:
```python
dp = IterableWrapper(["s3://BUCKET/images0.tar"])
# dp = dp.load_files_by_s3(region="us-east-1").load_from_tar(mode="r:")  # This is fast and works as expected
dp = dp.load_files_by_s3(region="us-east-1").load_from_tar(mode="r|")  # This is slow and doesn't terminate, it repeatedly yields certain files
start = time.time()
for x in dp:
    print(x)
print(time.time() - start)
```
Not sure if `mode="r|"` is incompatible with S3 DataPipe/SDK or there is something off with our implementation.

### Versions

main branch

cc: @ejguan

**Comment by ejguan** [comment]
Here are what I have found regarding S3Handler:

Originally I was expecting the returned stream from `S3handler` is non-seekable stream. But, it turns out that the whole archive/files will be dumped into memory based on the implementation here:
- C++ side: https://github.com/pytorch/data/blob/a435c7f5f7543e3614130eb2ecee520396b8efd2/torchdata/csrc/pybind/pybind.cpp#L28
- Python side: https://github.com/pytorch/data/blob/a435c7f5f7543e3614130eb2ecee520396b8efd2/torchdata/datapipes/iter/load/s3io.py#L135
And, that is the reason that the performance seems on parity with or without `BytesIO` in this [issue](https://github.com/pytorch/data/issues/657).

In order to make it streaming, we need to have a way to pybind C++ stream IO to python, which is non-trivial. See a code reference: https://github.com/CadQuery/OCP/blob/master/pystreambuf.h

However, it doesn't give us an answer about why it's not working with mode `r|` properly. I did test those two modes on a local tar archive, and both modes are working properly.

Then, it definitely a bug regarding S3Loader.

**Comment by NivekT** [comment]
The main branch is fine. The root cause is [here](https://github.com/pytorch/data/pull/764/files#diff-66cd262a8255d300ebf9545d21252142f118900419f78241d76733448d0d64c5).
